// Mock classes for workout_builder_provider_test.dart
// This file would normally be generated by build_runner

import 'package:mockito/mockito.dart' as _i1;
import 'package:flutter_bball_app/repositories/custom_workout_repository.dart' as _i2;
import 'package:flutter_bball_app/models/custom_workout_blueprint.dart' as _i3;

class MockCustomWorkoutRepository extends _i1.Mock implements _i2.CustomWorkoutRepository {
  @override
  Future<_i3.CustomWorkoutBlueprint> createWorkout(_i3.CustomWorkoutBlueprint? workout) =>
      super.noSuchMethod(Invocation.method(#createWorkout, [workout]),
          returnValue: Future.value(_i3.CustomWorkoutBlueprint(
            id: 'mock_id',
            name: 'Mock Workout',
            objective: 'Mock objective',
            estimatedDuration: 30,
            drills: [],
            authorId: 'mock_user',
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
            category: 'Ball Handling',
            difficulty: 'beginner',
            tags: [],
            isPublic: false,
            likes: 0,
            version: 1,
          )),
          returnValueForMissingStub: Future.value(_i3.CustomWorkoutBlueprint(
            id: 'mock_id',
            name: 'Mock Workout',
            objective: 'Mock objective',
            estimatedDuration: 30,
            drills: [],
            authorId: 'mock_user',
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
            category: 'Ball Handling',
            difficulty: 'beginner',
            tags: [],
            isPublic: false,
            likes: 0,
            version: 1,
          )));
  
  @override
  Future<void> saveDraft(_i3.CustomWorkoutBlueprint? draft) =>
      super.noSuchMethod(Invocation.method(#saveDraft, [draft]),
          returnValue: Future.value(),
          returnValueForMissingStub: Future.value());
  
  @override
  Future<_i3.CustomWorkoutBlueprint?> loadDraft() =>
      super.noSuchMethod(Invocation.method(#loadDraft, []),
          returnValue: Future.value(null));
  
  @override
  Future<void> clearDraft() =>
      super.noSuchMethod(Invocation.method(#clearDraft, []),
          returnValue: Future.value(),
          returnValueForMissingStub: Future.value());
}