// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmhqzngDKT3djCfrYJVeNSkmW40seXuy8',
    appId: '1:758737339378:web:69265f75b19f606a75a16b',
    messagingSenderId: '758737339378',
    projectId: 'flutter-bball-app',
    authDomain: 'flutter-bball-app.firebaseapp.com',
    storageBucket: 'flutter-bball-app.firebasestorage.app',
    measurementId: 'G-PEX8F8D5WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAhdMJEqi6ooDtfTAPigB8OAX1BzlnNd0',
    appId: '1:758737339378:android:aab23855bbbe3ffe75a16b',
    messagingSenderId: '758737339378',
    projectId: 'flutter-bball-app',
    storageBucket: 'flutter-bball-app.firebasestorage.app',
  );
}
