// Mock classes for custom_workout_repository_test.dart
// This file would normally be generated by build_runner

import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i2;
import 'package:cloud_firestore/cloud_firestore.dart' as _i3;

class MockSharedPreferences extends _i1.Mock implements _i2.SharedPreferences {
  @override
  String? getString(String? key) => super.noSuchMethod(Invocation.method(#getString, [key]));
  
  @override
  Future<bool> setString(String? key, String? value) => 
    super.noSuchMethod(Invocation.method(#setString, [key, value]), returnValue: Future.value(true));
  
  @override
  Future<bool> remove(String? key) => 
    super.noSuchMethod(Invocation.method(#remove, [key]), returnValue: Future.value(true));
}

class MockFirebaseFirestore extends _i1.Mock implements _i3.FirebaseFirestore {
  @override
  _i3.CollectionReference<Map<String, dynamic>> collection(String? collectionPath) =>
    super.noSuchMethod(Invocation.method(#collection, [collectionPath]), 
      returnValue: MockCollectionReference<Map<String, dynamic>>());
}

class MockCollectionReference<T> extends _i1.Mock implements _i3.CollectionReference<T> {
  @override
  _i3.DocumentReference<T> doc([String? path]) =>
    super.noSuchMethod(Invocation.method(#doc, [path]), 
      returnValue: MockDocumentReference<T>());
  
  @override
  Future<_i3.QuerySnapshot<T>> get() =>
    super.noSuchMethod(Invocation.method(#get, []), 
      returnValue: Future.value(MockQuerySnapshot<T>()));
  
  @override
  _i3.Query<T> where(dynamic field, {dynamic isEqualTo, dynamic isNotEqualTo, dynamic isLessThan, 
    dynamic isLessThanOrEqualTo, dynamic isGreaterThan, dynamic isGreaterThanOrEqualTo, 
    dynamic arrayContains, List<dynamic>? arrayContainsAny, List<dynamic>? whereIn, 
    List<dynamic>? whereNotIn, bool? isNull}) =>
    super.noSuchMethod(Invocation.method(#where, [field], {
      #isEqualTo: isEqualTo, #isNotEqualTo: isNotEqualTo, #isLessThan: isLessThan,
      #isLessThanOrEqualTo: isLessThanOrEqualTo, #isGreaterThan: isGreaterThan,
      #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo, #arrayContains: arrayContains,
      #arrayContainsAny: arrayContainsAny, #whereIn: whereIn, #whereNotIn: whereNotIn,
      #isNull: isNull
    }), returnValue: this);
}

class MockDocumentReference<T> extends _i1.Mock implements _i3.DocumentReference<T> {
  @override
  Future<void> set(T? data, [_i3.SetOptions? options]) =>
    super.noSuchMethod(Invocation.method(#set, [data, options]), 
      returnValue: Future.value());
  
  @override
  Future<void> update(Map<String, dynamic>? data) =>
    super.noSuchMethod(Invocation.method(#update, [data]), 
      returnValue: Future.value());
  
  @override
  Future<void> delete() =>
    super.noSuchMethod(Invocation.method(#delete, []), 
      returnValue: Future.value());
}

class MockDocumentSnapshot<T> extends _i1.Mock implements _i3.DocumentSnapshot<T> {
  @override
  T? data() => super.noSuchMethod(Invocation.method(#data, []));
}

class MockQuerySnapshot<T> extends _i1.Mock implements _i3.QuerySnapshot<T> {
  @override
  List<_i3.QueryDocumentSnapshot<T>> get docs =>
    super.noSuchMethod(Invocation.getter(#docs), returnValue: <_i3.QueryDocumentSnapshot<T>>[]);
}

class MockQueryDocumentSnapshot<T> extends _i1.Mock implements _i3.QueryDocumentSnapshot<T> {
  @override
  T data() => super.noSuchMethod(Invocation.method(#data, []));
}