// Mock classes for enhanced_workout_repository_test.dart
// This file would normally be generated by build_runner

import 'package:mockito/mockito.dart' as _i1;
import 'package:flutter_bball_app/repositories/custom_workout_repository.dart' as _i2;
import 'package:flutter_bball_app/models/custom_workout_blueprint.dart' as _i3;

class MockCustomWorkoutRepository extends _i1.Mock implements _i2.CustomWorkoutRepository {
  @override
  Future<List<_i3.CustomWorkoutBlueprint>> getAllWorkouts() =>
      super.noSuchMethod(Invocation.method(#getAllWorkouts, []),
          returnValue: Future.value(<_i3.CustomWorkoutBlueprint>[]),
          returnValueForMissingStub: Future.value(<_i3.CustomWorkoutBlueprint>[]));
  
  @override
  Future<_i3.CustomWorkoutBlueprint?> getWorkoutById(String? id) =>
      super.noSuchMethod(Invocation.method(#getWorkoutById, [id]),
          returnValue: Future.value(null));
  
  @override
  Future<List<_i3.CustomWorkoutBlueprint>> getWorkoutsByAuthor(String? authorId) =>
      super.noSuchMethod(Invocation.method(#getWorkoutsByAuthor, [authorId]),
          returnValue: Future.value(<_i3.CustomWorkoutBlueprint>[]),
          returnValueForMissingStub: Future.value(<_i3.CustomWorkoutBlueprint>[]));
  
  @override
  Future<List<_i3.CustomWorkoutBlueprint>> getPublicWorkouts() =>
      super.noSuchMethod(Invocation.method(#getPublicWorkouts, []),
          returnValue: Future.value(<_i3.CustomWorkoutBlueprint>[]),
          returnValueForMissingStub: Future.value(<_i3.CustomWorkoutBlueprint>[]));
  
  @override
  Future<List<_i3.CustomWorkoutBlueprint>> searchWorkouts(String? query) =>
      super.noSuchMethod(Invocation.method(#searchWorkouts, [query]),
          returnValue: Future.value(<_i3.CustomWorkoutBlueprint>[]),
          returnValueForMissingStub: Future.value(<_i3.CustomWorkoutBlueprint>[]));
  
  @override
  Future<List<_i3.CustomWorkoutBlueprint>> getWorkoutsByCategory(String? category) =>
      super.noSuchMethod(Invocation.method(#getWorkoutsByCategory, [category]),
          returnValue: Future.value(<_i3.CustomWorkoutBlueprint>[]),
          returnValueForMissingStub: Future.value(<_i3.CustomWorkoutBlueprint>[]));
  
  @override
  Future<List<_i3.CustomWorkoutBlueprint>> getWorkoutsByDifficulty(String? difficulty) =>
      super.noSuchMethod(Invocation.method(#getWorkoutsByDifficulty, [difficulty]),
          returnValue: Future.value(<_i3.CustomWorkoutBlueprint>[]),
          returnValueForMissingStub: Future.value(<_i3.CustomWorkoutBlueprint>[]));
  
  @override
  Future<List<_i3.CustomWorkoutBlueprint>> getWorkoutsByTags(List<String>? tags) =>
      super.noSuchMethod(Invocation.method(#getWorkoutsByTags, [tags]),
          returnValue: Future.value(<_i3.CustomWorkoutBlueprint>[]),
          returnValueForMissingStub: Future.value(<_i3.CustomWorkoutBlueprint>[]));
}