// Mock classes for drill_library_screen_test.dart
// This file would normally be generated by build_runner

import 'package:mockito/mockito.dart' as _i1;
import 'package:flutter_bball_app/services/drill_library_service.dart' as _i2;
import 'package:flutter_bball_app/models/drill_template.dart' as _i3;
import 'package:flutter_bball_app/models/drill.dart' as _i4;

class MockDrillLibraryService extends _i1.Mock implements _i2.DrillLibraryService {
  @override
  Future<List<_i3.DrillTemplate>> getAllTemplates() =>
      super.noSuchMethod(Invocation.method(#getAllTemplates, []),
          returnValue: Future.value(<_i3.DrillTemplate>[]),
          returnValueForMissingStub: Future.value(<_i3.DrillTemplate>[]));
  
  @override
  Future<List<_i3.DrillTemplate>> getTemplatesByCategory(String? category) =>
      super.noSuchMethod(Invocation.method(#getTemplatesByCategory, [category]),
          returnValue: Future.value(<_i3.DrillTemplate>[]),
          returnValueForMissingStub: Future.value(<_i3.DrillTemplate>[]));
  
  @override
  Future<List<_i3.DrillTemplate>> getTemplatesByType(String? type) =>
      super.noSuchMethod(Invocation.method(#getTemplatesByType, [type]),
          returnValue: Future.value(<_i3.DrillTemplate>[]),
          returnValueForMissingStub: Future.value(<_i3.DrillTemplate>[]));
  
  @override
  Future<List<_i3.DrillTemplate>> searchTemplates(String? query) =>
      super.noSuchMethod(Invocation.method(#searchTemplates, [query]),
          returnValue: Future.value(<_i3.DrillTemplate>[]),
          returnValueForMissingStub: Future.value(<_i3.DrillTemplate>[]));
  
  @override
  Future<List<_i3.DrillTemplate>> filterTemplates({
    String? category,
    String? type,
    String? difficulty,
    List<String>? tags,
  }) =>
      super.noSuchMethod(Invocation.method(#filterTemplates, [], {
        #category: category,
        #type: type,
        #difficulty: difficulty,
        #tags: tags,
      }),
          returnValue: Future.value(<_i3.DrillTemplate>[]),
          returnValueForMissingStub: Future.value(<_i3.DrillTemplate>[]));
  
  @override
  Future<_i3.DrillTemplate?> getTemplateById(String? id) =>
      super.noSuchMethod(Invocation.method(#getTemplateById, [id]),
          returnValue: Future.value(null));
  
  @override
  Future<_i4.Drill> createDrillFromTemplate(
    _i3.DrillTemplate? template, {
    Map<String, dynamic>? customConfig,
  }) =>
      super.noSuchMethod(
          Invocation.method(#createDrillFromTemplate, [template], {#customConfig: customConfig}),
          returnValue: Future.value(_i4.Drill(
            drillId: 'mock_id',
            name: 'Mock Drill',
            description: 'Mock Description',
            type: 'TIMED',
            config: {},
          )),
          returnValueForMissingStub: Future.value(_i4.Drill(
            drillId: 'mock_id',
            name: 'Mock Drill',
            description: 'Mock Description',
            type: 'TIMED',
            config: {},
          )));
  
  @override
  Future<List<String>> getCategories() =>
      super.noSuchMethod(Invocation.method(#getCategories, []),
          returnValue: Future.value(<String>[]),
          returnValueForMissingStub: Future.value(<String>[]));
  
  @override
  Future<List<String>> getDrillTypes() =>
      super.noSuchMethod(Invocation.method(#getDrillTypes, []),
          returnValue: Future.value(<String>[]),
          returnValueForMissingStub: Future.value(<String>[]));
  
  @override
  Future<List<String>> getDifficulties() =>
      super.noSuchMethod(Invocation.method(#getDifficulties, []),
          returnValue: Future.value(<String>[]),
          returnValueForMissingStub: Future.value(<String>[]));
  
  @override
  Future<bool> validateDrillConfig(String? type, Map<String, dynamic>? config) =>
      super.noSuchMethod(Invocation.method(#validateDrillConfig, [type, config]),
          returnValue: Future.value(false),
          returnValueForMissingStub: Future.value(false));
  
  @override
  Future<Map<String, dynamic>> getDefaultConfig(String? type) =>
      super.noSuchMethod(Invocation.method(#getDefaultConfig, [type]),
          returnValue: Future.value(<String, dynamic>{}),
          returnValueForMissingStub: Future.value(<String, dynamic>{}));
}