// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_bball_app/test/screens/active/widgets/timed_drill_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:flutter_bball_app/models/drill_result.dart' as _i3;
import 'package:flutter_bball_app/models/workout_blueprint.dart' as _i5;
import 'package:flutter_bball_app/services/settings_service.dart' as _i4;
import 'package:flutter_bball_app/services/workout_state.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WorkoutState].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutState extends _i1.Mock implements _i2.WorkoutState {
  MockWorkoutState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isWorkoutStarted =>
      (super.noSuchMethod(
            Invocation.getter(#isWorkoutStarted),
            returnValue: false,
          )
          as bool);

  @override
  bool get isWorkoutComplete =>
      (super.noSuchMethod(
            Invocation.getter(#isWorkoutComplete),
            returnValue: false,
          )
          as bool);

  @override
  bool get isPaused =>
      (super.noSuchMethod(Invocation.getter(#isPaused), returnValue: false)
          as bool);

  @override
  int get totalDrills =>
      (super.noSuchMethod(Invocation.getter(#totalDrills), returnValue: 0)
          as int);

  @override
  List<_i3.DrillResult> get results =>
      (super.noSuchMethod(
            Invocation.getter(#results),
            returnValue: <_i3.DrillResult>[],
          )
          as List<_i3.DrillResult>);

  @override
  int get currentDrillIndex =>
      (super.noSuchMethod(Invocation.getter(#currentDrillIndex), returnValue: 0)
          as int);

  @override
  int get resetDrillCounter =>
      (super.noSuchMethod(Invocation.getter(#resetDrillCounter), returnValue: 0)
          as int);

  @override
  double get workoutProgress =>
      (super.noSuchMethod(Invocation.getter(#workoutProgress), returnValue: 0.0)
          as double);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSettingsService(_i4.SettingsService? settingsService) =>
      super.noSuchMethod(
        Invocation.method(#setSettingsService, [settingsService]),
        returnValueForMissingStub: null,
      );

  @override
  void togglePause() => super.noSuchMethod(
    Invocation.method(#togglePause, []),
    returnValueForMissingStub: null,
  );

  @override
  void startWorkout(_i5.WorkoutBlueprint? blueprint) => super.noSuchMethod(
    Invocation.method(#startWorkout, [blueprint]),
    returnValueForMissingStub: null,
  );

  @override
  void nextDrill() => super.noSuchMethod(
    Invocation.method(#nextDrill, []),
    returnValueForMissingStub: null,
  );

  @override
  void logTimedDrill() => super.noSuchMethod(
    Invocation.method(#logTimedDrill, []),
    returnValueForMissingStub: null,
  );

  @override
  void logRepBasedDrill({required int? makes}) => super.noSuchMethod(
    Invocation.method(#logRepBasedDrill, [], {#makes: makes}),
    returnValueForMissingStub: null,
  );

  @override
  void logMakeTargetTimedDrill({required int? elapsedSeconds}) =>
      super.noSuchMethod(
        Invocation.method(#logMakeTargetTimedDrill, [], {
          #elapsedSeconds: elapsedSeconds,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void logReadAndReactDrill({required int? totalReps}) => super.noSuchMethod(
    Invocation.method(#logReadAndReactDrill, [], {#totalReps: totalReps}),
    returnValueForMissingStub: null,
  );

  @override
  void endWorkout() => super.noSuchMethod(
    Invocation.method(#endWorkout, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> savePartialWorkout() =>
      (super.noSuchMethod(
            Invocation.method(#savePartialWorkout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void discardWorkout() => super.noSuchMethod(
    Invocation.method(#discardWorkout, []),
    returnValueForMissingStub: null,
  );

  @override
  void previousDrill() => super.noSuchMethod(
    Invocation.method(#previousDrill, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetCurrentDrill() => super.noSuchMethod(
    Invocation.method(#resetCurrentDrill, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
